### ISSUE TITLE
[Feature Request] Auto-fetch and cache arXiv papers

### ISSUE THREAD

**Issue by chingswy** [Xuer04/notion-arxiv-enhancer#1]
Dear author,

First of all, I would like to thank you for sharing this repository for updating Notion. It has been very helpful to me.

I would like to request a new feature. I would like the ability to automatically fetch updated arXiv paper links daily and cache them for download locally. This would save me time from manually downloading papers.

Thank you again for your contribution and I look forward to your response.

**Comment by cxzhou35** [comment]
Thank you for making this great request.

Since there are many articles updated on arXiv every day. Wouldn't it be better if we could retrieve the latest arXiv articles based on **"specific topics"** like novel view synthesis?

I will implement this feature when I have time, please stay tuned. :)

**Comment by chingswy** [comment]
You can just retrieve the some specific topic `cs.CV`.

**Comment by cxzhou35** [comment]
Sounds great, this has made the work much easier.

**Comment by cxzhou35** [comment]
> Dear author,
> 
> First of all, I would like to thank you for sharing this repository for updating Notion. It has been very helpful to me.
> 
> I would like to request a new feature. I would like the ability to automatically fetch updated arXiv paper links daily and cache them for download locally. This would save me time from manually downloading papers.
> 
> Thank you again for your contribution and I look forward to your response.

Sorry for the wait, I have already implemented this feature, please see the details in the 'Features' section of the documentation here ➡️ [Features](https://github.com/Xuer04/notion-arxiv-enhancer/#Features)

If you have any further questions, please feel free to contact me. :)
